from __future__ import annotations

from .rules import (
    extrair_alunos_sem_cpf,
    find_matriculas_duplicadas,
    levantamento_cor_raca,
    validate_aluno,
    validate_gestor,
    validate_profissionais,
    validate_turmas,
    validate_unidades,
)

VALIDATIONS: dict[str, dict] = {
    "unidades": {
        "key": "unidades",
        "state_prefix": "vu_",
        "title": "Geração de Relatórios Gerais e de Inconsistências - Cadastro de Unidades",
        "subtitle": "Verifica inconsistências nos dados cadastrais das unidades escolares no Educacenso.",
        "requires_dates": True,
        "validate": validate_unidades,
    },
    "gestor": {
        "key": "gestor",
        "state_prefix": "vg_",
        "title": "Geração de Relatórios Gerais e de Inconsistências - Cadastro de Gestor",
        "subtitle": "Verifica inconsistências nos dados cadastrais do gestor escolar no Educacenso.",
        "requires_dates": False,
        "validate": validate_gestor,
    },
    "turmas": {
        "key": "turmas",
        "state_prefix": "vt_",
        "title": "Geração de Relatórios Gerais e de Inconsistências - Cadastro de Turmas",
        "subtitle": "Verifica inconsistências nos dados das turmas declaradas no Educacenso.",
        "requires_dates": False,
        "source": "zip",
        "split_tipo_turma": True,
        "validate": validate_turmas,
        "expected_columns": [
            "Ordem",
            "Código da turma",
            "Nome da turma",
            "Tipo de mediação didático-pedagógica",
            "Tipo de turma",
            "Etapa Agregada",
            "Etapa de ensino",
            "Carga horária total do curso",
            "Carga horária semanal (hh:mm)",
            "Formas de organização da turma",
            "Local de funcionamento diferenciado da turma",
            "Dias da semana e horário de funcionamento",
            "Turma de Educação Especial (classe especial)",
            "Turma de Educação Bilingue de Surdos (classe bilingue de surdos)",
            "Formação por Alternância (proposta pedagógica de formação por alternância tempo - escola e tempo - comunidade)",
            "Áreas do conhecimento/componentes curriculares",
            "Organização curricular da turma",
            "Área(s) do itinerário formativo",
            "Tipo de curso do itinerário de formação técnica e profissional",
            "Código e nome do curso técnico",
            "Atividade (s) complementar (es)",
            "Quantidade de Alunos (as)",
            "Quantidade de Profissionais escolares",
        ],
    },
    "aluno": {
        "key": "aluno",
        "state_prefix": "va_",
        "title": "Geração de Relatórios Gerais e de Inconsistências - Cadastro de Aluno",
        "subtitle": "Verifica inconsistências nos dados dos alunos declarados no Educacenso.",
        "requires_dates": False,
        "source": "zip",
        "split_aluno": True,
        "validate": validate_aluno,
        "find_duplicadas": find_matriculas_duplicadas,
        "levantamento_cor_raca": levantamento_cor_raca,
        "extrair_sem_cpf": extrair_alunos_sem_cpf,
        "expected_columns": [
            "Ordem",
            "Identificação única",
            "Nome",
            "Data de nascimento",
            "CPF",
            "Nacionalidade",
            "Município-UF de nascimento",
            "Cor/Raça",
            "Povo indígena",
            "Sexo",
            "Tipo(s) de deficiência(s), transtorno(s) do espectro autista e altas habilidades ou superdotação",
            "Tipo(s) de transtorno(s) que impacta(m) o desenvolvimento da aprendizagem",
            "Recursos para o uso do(a) aluno(a) em sala de aula para a participação em avaliações do Inep (Saeb)",
            "Localização/Zona de residência",
            "Localização diferenciada de residência",
            "Código da Matrícula",
            "Código da turma",
            "Nome da turma",
            "Etapa de ensino",
            "Tipo de atendimento educacional especializado (AEE)",
            "Recebe atendimento educacional em regime hospitalar ou domiciliar",
            "Transporte escolar (Sim/Não)",
            "Poder Público responsável",
            "Tipo de veículo utilizado no transporte escolar",
            "Etapa de vínculo do(a) aluno(a) (Para turmas do tipo multi)",
            "Carga horária integralizada pelo(a) aluno(a) no curso técnico ou de qualificação profissional",
        ],
    },
    "profissionais": {
        "key": "profissionais",
        "state_prefix": "vp_",
        "title": "Geração de Relatórios Gerais e de Inconsistências - Cadastro de Profissionais Escolares",
        "subtitle": "Verifica inconsistências nos dados dos profissionais escolares declarados no Educacenso.",
        "requires_dates": False,
        "source": "zip",
        "split_profissionais": True,
        "validate": validate_profissionais,
        "expected_columns": [
            "Ordem",
            "Identificação única",
            "Nome",
            "Data de Nascimento",
            "CPF",
            "Nacionalidade",
            "Cor/Raça",
            "Povo Indígena",
            "Sexo",
            "Tipo(s) de deficiência(s), transtorno(s) do espectro autista e altas habilidades ou superdotação",
            "Localização/Zona de residência",
            "Localização diferenciada de residência",
            "Maior nível de escolaridade concluído",
            "Tipo de ensino médio cursado",
            "Pós-Graduação concluída",
            "Formação/Complementação Pedagógica",
            "Outros cursos específicos (Formação continuada com no mínimo 80 horas)",
            "Código da turma",
            "Nome da Turma",
            "Etapa de ensino",
            "Situação Funcional / Regime de contratação / Tipo de vínculo",
            "Função que exerce na turma",
            "Áreas do conhecimento/componentes curriculares que leciona (FGB)",
            "Área(s) do Itinerário formativo que leciona (IFA)",
            "Tipo do curso do itinerário de formação técnica e profissional que leciona",
        ],
    },
}
